name: tfm-failure
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip

  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - seaborn
  - catboost

  - pip:
      - tqdm
      - pyyaml
      - pytabkit
      - tabicl>=2.1
      - tabpfn>=8.0.1
